name: "YZFrame CI"

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  iOS:
    name: Test iOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: iOS
        run: fastlane ci_commit configuration:Debug --env ios13_xcode11
